# Generated by Django 5.2 on 2025-04-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
