# Generated by Django 4.2.9 on 2025-04-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='hotel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
